// AUTO-GENERATED by scripts/build-posts-manifest.mjs — do not edit by hand.
// Source of truth is the frontmatter in src/content/posts/*.mdx.
// Regenerate with `npm run posts:build` (also runs from prebuild/predev).

import type { Post } from "@/lib/content/posts";

export const generatedPosts: Post[] = [
  {
    "slug": "software-house-in-sialkot",
    "title": "Software house in Sialkot: what working with Granyyte is like",
    "description": "Looking for a software company in Sialkot? Granyyte builds apps, websites and custom business systems for Sialkot businesses and clients abroad.",
    "date": "2026-09-15",
    "readingTime": "5 min read",
    "tags": [
      "Sialkot",
      "Software House",
      "Custom Software"
    ],
    "hub": "industry-software",
    "targetKeyword": "software house in sialkot",
    "relatedService": "/software-development-sialkot",
    "relatedServiceLabel": "Custom software development in Sialkot"
  },
  {
    "slug": "custom-software-vs-off-the-shelf",
    "title": "Custom Software vs. Off-the-Shelf: A Decision Guide",
    "description": "Paying for five SaaS tools that almost fit? A practical framework for deciding when custom software pays for itself, plus why owning software you can ship in weeks changes the math.",
    "date": "2026-07-02",
    "readingTime": "3 min read",
    "tags": [
      "Custom Software",
      "Business",
      "Strategy"
    ],
    "hub": "custom-vs-saas",
    "targetKeyword": "custom software vs off the shelf",
    "relatedService": "/services/custom-software"
  },
  {
    "slug": "flutterflow-vs-native-development",
    "title": "FlutterFlow vs. Native Development: What to Choose in 2026",
    "description": "Native means two separate codebases, more time, and more budget. With Flutter and FlutterFlow you ship the same product in roughly three times less time and money. Here's the honest breakdown from a certified FlutterFlow expert.",
    "date": "2026-07-02",
    "readingTime": "4 min read",
    "tags": [
      "FlutterFlow",
      "Mobile Development",
      "Strategy"
    ],
    "hub": "flutterflow",
    "targetKeyword": "flutterflow vs native development",
    "relatedService": "/services/mobile-app-development"
  }
];
